USE [DATABASE]
GO

SELECT DISTINCT
	BASE.TABLE_CATALOG, 
	BASE.OBJECT_NAME,
	BASE.COLUMN_NAME,
	BASE.DATA_TYPE

FROM(SELECT 
		TABLS.TABLE_CATALOG,
		CONCAT(TABLS.TABLE_CATALOG, '.', COLMS.TABLE_SCHEMA, '.', COLMS.TABLE_NAME) OBJECT_NAME,
		COLMS.COLUMN_NAME, 
		COLMS.ORDINAL_POSITION,
		COLMS.DATA_TYPE
	
	FROM information_schema.TABLES TABLS
	
	LEFT JOIN information_schema.COLUMNS COLMS
		ON COLMS.TABLE_SCHEMA = TABLS.table_schema 
		AND COLMS.table_name = TABLS.table_name
	
	) BASE

WHERE 0 = 0
--	AND BASE.TABLE_CATALOG LIKE '%XXX%'	--Database to look in
--	AND BASE.OBJECT_NAME LIKE '%XXX'		--View or Table name
--	AND BASE.COLUMN_NAME LIKE '%XXX%'		--Column name


;

